/*###DISCUSSION: Dual-mode game functionality: Morphing and gameplay
=== REWRITE TODO ===
- Finally get fucking mesh in... too many vert groups per bone! (Because bad body morph??)
- Continue CBody ctor to split everything
- Swtich to real body... work on other meshes

=== NEXT ===

=== TODO ===

=== LATER ===

=== IMPROVE ===

=== DESIGN ===
- Best possible design would be:
	- Not requring expensive rebuild for anything other than sex change
		- Store fully-realized bodies (man, woman, shemale) in Blender file??
			- Store as a cache and save?  (Could get too many when we have many genitals, bodies)
		- Rebuild of softbody a part of the complexity... could push morph to soft bodies and have them re-create their PhysX2 objects??
	-? Having both morphing and simulated bodies on screen?

- Considerations:
	- How to morph shemale & man because of penis attach and underwear design???
	- Morphing of cloth around cock basically means softbody and penis collider created as usual: Breast different!
	- Keeping CBody separate simplifies hotspot management, game actions, etc.
	- For real morphing flexibility we also have to take body col and cloth collider in account!!

- Ideas:
	- Don't even have our current (limited) morphing body... Apply morphs to real body all the time?
		- Morphs have to traverse detached body parts like breasts and penis
		- In this mode soft bodies would be rigid... coming out they become simulated.
		- Hotspots and actors a problem?  (easy to fix??)

- Strategy:
	- We have a go to reuse CBody current runtime architecture with the softbodies 'disabled' and reloadable from Blender...
		- We need a wholistic way to morph the source body (with penis / vagina) attached and have all the parts update themselves.
		- (This way we can apply morphs that affect several morphed parts)
	- 1. Assemble final 'morph body' -> proper penis, vagina put in.
	- 2. Before parts are detached, create a layer on the morph body so detached parts can update themselves.
	- 3. When a morph is applied to morph body, all detached parts are requested to update themselves.
	- 4. Collider meshes (body col, cloth col, breast col) updates themselves last from their detached part.

=== QUESTIONS ===
- Decide on Blender body storage... fully realized already?  (saves time)

=== IDEAS ===

=== LEARNED ===

=== PROBLEMS ===

=== PROBLEMS??? ===

=== WISHLIST ===

*/


using UnityEngine;
using System;
using System.IO;
using System.Collections.Generic;



public class CBody : IObject, IHotSpotMgr { 		// Manages a 'body':  Does not actually represent a mesh (most of the skinned body represtend by _oBodySkinnedMesh;
	// The main purpose of this class is to act as a bridge between the bone structure used for animation of the main skinned mesh and enable our connected soft-body parts to move along with us via our rim mesh and the pins it updates with PhysX

	//---------------------------------------------------------------------------	VISIBLE PROPERTIES
	public 	int					_nBodyID;				// The 0-based numeric ID of our body.  Extremely important.  Matches Blender's CBody.nBodyID as well
	public	string				_sBlenderInstancePath_CBody;				// The Blender instance path where our corresponding CBody is access (from global scope)
	public	string				_sBodyPrefix;			// The 'body prefix' string used to identify Blender & Unity node for this body (Equals to 'BodyA', 'BodyB', 'BodyC', etc)
	public 	string				_sHumanCharacterName;	// The human first-name given to this character... purely cosmetic
	public  GameObject			_oBodyRootGO;			// The root game object of every Unity object for this body.  (Created from prefab)
	public 	CObject				_oObj;					// The user-configurable object representing this body.
	public 	CBSkin				_oBodySkinnedMesh;		// The main skinned mesh representing most of the body (e.g. everything except detached soft body parts, head, hair, clothing, etc)
//	public 	CBMesh				_oBodySource;           // The source body unmodified in any way.  (Currently used to extract normals for softbody rims)
    public  CBSkin              _oBodyFlexCldr;         // A reduced-geometry re-mesh of the skinned body generated by Blender that forms the skinned particles responsible to push away other Flex particles from body.
    public  CHeadLook			_oHeadLook;             // Object in charge of moving head toward points of interest
	public 	EBodySex			_eBodySex;				// The body's sex (man, woman, shemale)
	public 	bool				_bIsCumming;            // Character is currently cumming.  Set globally
    public  GameObject          _oHairGO;               // Reference to the hair game object we mount on head at init.

    //---------------------------------------------------------------------------	IMPLEMENTATION MEMBERS
    public 	CHotSpot			_oHotSpot;				// Hotspot at the head of the character.  Enables user to change the important body properties by right-clicking on the head
	//public 	CBSkinBaked 		_oBSkinRim;				//###DESIGN!!!! Rename the old 'rim'?
	///public 	CBBodyCol			_oBodyCol;				// The full 'Body Collider' that repells fluid, hands, softbody breasts, etc from this human body.	###OPT!!!: Cut into 'body parts' that activate/deactivate when something is near
	public 	Transform			_oBonesT;				// The 'Root' bone node right off of our top-level node with the name of 'Bones' = The body's bone tree
	public 	Transform			_oBaseT;				// The 'Root' pin node right off of our top-level node with the name of 'Base' = The body's pins (controlling key bones through PhysX joints)
	public 	CScriptPlay			_oScriptPlay;			// Scripting interpreter in charge of loading user scripts that programmatically control this body (poses also load this way)
	public 	CFace				_oFace;
	public 	string				_sNamePose;				// The name of the current loaded pose (Same as filename in /Poses directory)

	//---------------------------------------------------------------------------	SOFT BODY PARTS
	public	CBreastL 		    _oBreastL;					// The left and right breasts as softbodies
	public	CBreastR 		    _oBreastR;
	public	CPenis				_oPenis;
    public  CVagina				_oVagina;
	public	List<CBSoft>		_aSoftBodies	= new List<CBSoft>();		// List of all our _oSoftBodiesXXX above... used to simplify iterations.

	//---------------------------------------------------------------------------	CLOTHING		//###DESIGN: ###CHECK?
	public	List<CBCloth>		_aCloths		= new List<CBCloth>();		// List of our simulated cloth.  Used to iterate during runtime

	//---------------------------------------------------------------------------	ACTORS
	public 	CActorNode			_oActor_Base;			// The smart 'actors' associated with our body.  Adds much intelligent functionality!
	public 	CActorNode			_oActor_Torso;
	public 	CActorPelvis		_oActor_Pelvis;
	public 	CActorChest			_oActor_Chest;
	public 	CActorArm 			_oActor_ArmL;
	public 	CActorArm 			_oActor_ArmR;
	public 	CActorLeg 			_oActor_LegL;
	public 	CActorLeg 			_oActor_LegR;
	public 	List<CActor>		_aActors = new List<CActor>();		// An array containing all the _oActor_xxx elements above.  Used to simplify iterations.

	//---------------------------------------------------------------------------	SCRIPT ACCESS
	public 	CObject				 Base;		// Flattened references to the oObj CObject member of our actors.  Done to offer scripting runtime simplified access to our scriptable members using friendlier names.
	public 	CObject				 Torso;
	public 	CObject				 Chest;
	public 	CObject				 Pelvis;
	public 	CObject				 ArmL;
	public 	CObject				 ArmR;
	public 	CObject				 LegL;
	public 	CObject				 LegR;
	public 	CObject				 Face;
	public 	CObject				 Penis;

	//---------------------------------------------------------------------------	KEYBOARD HOOKS
	//CKeyHook _oKeyHook_PenisBaseUpDown;
	//CKeyHook _oKeyHook_PenisShaftUpDown;
	//CKeyHook _oKeyHook_PenisDriveStrengthMax;
	CKeyHook _oKeyHook_ChestUpDown;

	//---------------------------------------------------------------------------	MISC
	CActorArm _oArm_SettingRaycastPin;      // The arm we are currently searching for raycasting hand target (when user placing hands)

	//CClothEdit _oClothEdit_HACK;
    //CFlexCloth_OBS _oFlexCloth_HACK;

    //---------------------------------------------------------------------------
    public bool _bForMorphingOnly;                              // Body is currently in 'morphing mode' only (not gameplay) ###DEV To enum?

	public const int C_Unity2Blender_MaxVerts = 5000;			// Maximum number of verts for Unity2Blender mesh       ###OBS ###TUNE ###IMPROVE: Create damn mesh on demand!! ###MOVE
    public CUICanvas[] _aUICanvas = new CUICanvas[2];           // The UI canvases that display various user interface panels to provide end-user edit capability on this body.  One for each left / right.


	public CBody(int nBodyID) {
		_nBodyID = nBodyID;
		_sBlenderInstancePath_CBody = "CBody_GetBody(" + _nBodyID.ToString() + ")";                 // Simplify access to Blender CBody instance			####MOVE??

		//bool bForMorphingOnly = false;  //###JUNK (CGame.INSTANCE._GameMode == EGameModes.MorphNew_TEMP);				//####DEV!!!!
		Debug.Log(string.Format("+ Creating body #{0}", _nBodyID));


		_sBodyPrefix = CBody.GetNameGameBodyFromPrefix(_nBodyID);		// The name of the Blender-side object that will store our property is the base mesh named like 'BodyA', 'BodyB', etc
		_oObj = new CObject(this, _nBodyID, typeof(EBodyDef), "Body", null, _sBodyPrefix);	//###NOTE: Note that this is a 'Blender-enabled' CObject with some properties existing in Blender!
		_oObj.PropGroupBegin("", "", true);
		_oObj.PropAdd(EBodyDef.Sex,				"Sex",				typeof(EBodySex), (int)EBodySex.Woman,	"", CProp.Local);
		_oObj.PropAdd(EBodyDef.ClothingTop,		"Top Clothing",		typeof(EBodyClothingTop_HACK), 0, "", CProp.Local);		//###HACK!!!!
		_oObj.PropAdd(EBodyDef.ClothingBottom,	"Bottom Clothing",	typeof(EBodyClothingBottom_HACK), 0, "", CProp.Local + CProp.Hide);	//###BROKEN: Need to switch off vagina soft body!!
		_oObj.PropAdd(EBodyDef.Hair,			"Hair",				typeof(EBodyHair), 0,	"", CProp.Local);
		_oObj.PropAdd(EBodyDef.BtnUpdateBody,	"Update Body",		0,	"", CProp.Local | CProp.AsButton);
		_oObj.PropAdd(EBodyDef.BreastSize,		"Breast Size",		1.0f, 0.5f, 2.5f, "", CProp.Local);
		_oObj.FinishInitialization();

		//=== Give some reasonable defaults to use when game loads ===		###TODO: Load these from the user's last used body definitions!		####TEMP ####DESIGN: Load from user pref or file?  NOT IN CODE!!
		if (_nBodyID == 0) {
			_oObj.PropSet(EBodyDef.Sex,				(int)EBodySex.Shemale);
			_oObj.PropSet(EBodyDef.Hair, (int)EBodyHair.TiedUp);
//			oObj.PropSet(EBodyDef.Hair, (int)EBodyHair.Messy);
//			oObj.PropFind(EBodyDef.ClothingTop)._nPropFlags |= CProp.Hide;		//###HACK!!!!
//			oObj.PropFind(EBodyDef.BreastSize)._nPropFlags |= CProp.Hide;
//			oObj.PropFind(EBodyDef.Hair)._nPropFlags |= CProp.Hide;
		} else {
			//_oObj.PropSet(EBodyDef.Sex,				(int)EBodySex.Man);		####REVB
			_oObj.PropSet(EBodyDef.Sex,				(int)EBodySex.Shemale);
			//oObj.PropSet(EBodyDef.ClothingTop, (int)EBodyClothingTop_HACK.TiedTop);
			_oObj.PropSet(EBodyDef.Hair, (int)EBodyHair.TiedUp);
			//if (CGame.INSTANCE._bRunningInEditor)		//###TEMP! :)
			//	oObj.PropSet(EBodyDef.BreastSize, 1.3f);
		}
	}

	public void DoInitialize() { 
		//=== Create default values for important body parameters from the sex ===
		string sMeshSource = "";
		string sNameSrcGenitals = "";
		EBodySex eBodySex = (EBodySex)_oObj.PropGet((int)EBodyDef.Sex);

		if (eBodySex == EBodySex.Man) {
			sMeshSource = "ManA"; 
			_sHumanCharacterName = (_nBodyID == 0) ? "Karl" : "Brent";          //###IMPROVE: Database of names?  From user???
		} else {
			sMeshSource = "WomanA";
			_sHumanCharacterName = (_nBodyID == 0) ? "Emily" : "Eve";
		}

		switch (eBodySex) {									//###CHECK	####TEMP ####DESIGN: Loaded from file or user top-level selection! ####DESIGN: Public properties?
			case EBodySex.Man:
				sNameSrcGenitals = "PenisM-Erotic9-A-Big";
				break;
			case EBodySex.Woman:
				sNameSrcGenitals = "Vagina-Erotic9-A";					//###DESIGN??? Crotch and not vagina???
				break;
			case EBodySex.Shemale:
				sNameSrcGenitals = "PenisW-Erotic9-A-Big";				//###TODO: Comes from GUI!
				break;
		}


		//===== CREATE THE BODY IN BLENDER =====  
		CGame.gBL_SendCmd("CBody", "CBody_Create(" + _nBodyID.ToString() + ", '" + sMeshSource + "', '" + eBodySex.ToString() + "','" + sNameSrcGenitals + "', " + C_Unity2Blender_MaxVerts.ToString() + ")");		// This new instance is an extension of this Unity CBody instance and contains most instance members

        //=== Instantiate the proper prefab for our body type (Man or Woman), which defines our bones and colliders ===
        GameObject oBodyTemplateGO = Resources.Load("Prefabs/Prefab" + sMeshSource, typeof(GameObject)) as GameObject;		//###TODO: Different gender / body types enum that matches Blender	//oBody._sMeshSource + 
		_oBodyRootGO = GameObject.Instantiate(oBodyTemplateGO) as GameObject;
		_oBodyRootGO.SetActive(true);			// Prefab is stored with top object deactivated to ease development... activate it here...

        //if (_nBodyID == 1) 
        //    _oBodyRootGO.transform.position = new Vector3(0, 0, 1.5f);      //###F ###HACK!!!!!!

        //=== Obtain references to needed sub-objects of our prefab ===
        _oBonesT	= _oBodyRootGO.transform.FindChild("Bones");			// Set key nodes of Bones and Base we'll need quick access to over and over.
		_oBaseT		= _oBodyRootGO.transform.FindChild("Base");







        //===== DETACHED SOFTBODY PARTS PROCESSING =====
        _aSoftBodies.Add(_oBreastL = (CBreastL)CBSoft.Create(this, typeof(CBreastL), "chest"));        //###DEVNOW
        _aSoftBodies.Add(_oBreastR = (CBreastR)CBSoft.Create(this, typeof(CBreastR), "chest"));
		//if (eBodySex == EBodySex.Woman) {
  //          _aSoftBodies.Add(_oVagina = (CVagina)CBSoft.Create(this, typeof(CVagina), "chest/abdomen/hip"));
  //      } else {
            _aSoftBodies.Add(_oPenis = (CPenis)CBSoft.Create(this, typeof(CPenis), "chest/abdomen/hip"));
  //      }

        ////####TEMP ####DESIGN ####TEMP ####MOVE
        //_aCloths.Add(CBCloth.Create(this, "MyShirt", "Shirt", "HACK-Cloth-TankTop", "_ClothSkinnedArea_ShoulderTop"));    //_ClothSkinnedArea_Top
        ///_aCloths.Add(CBCloth.Create(this, "MyShirt", "Shirt", "BodySuit", "_ClothSkinnedArea_ShoulderTop"));    //_ClothSkinnedArea_Top
        ////_aCloths.Add(CBCloth.Create(this, "Rough1-Holds"));
        ////_aCloths.Add(CBCloth.Create(this, "Rough2-Spreads"));
        ////_aCloths.Add(CBCloth.Create(this, "BodySuit-Top-Trimmed"));
        ////////////###DEV _aCloths.Add(CBCloth.Create(this, "FullShirt"));


        
        
        
        
        
        
        ////=== Create the various soft-body mesh parts that are dependant on the body sex ===
        ////###IMPROVE!!!! Parse array of Blender-pushed softbody into our parts (instead of pulling like below?)
        //if (_bForMorphingOnly == false) {
        //	if (_eBodySex == EBodySex.Woman || _eBodySex == EBodySex.Shemale) {
        //		_aSoftBodies.Add(_oBreastL = (CBreastBase)CBMesh.Create(null, this, _sNameGameBody, "_Detach_Breasts", "Client", "gBL_GetMesh", "'SkinInfo'", typeof(CBreastBase)));           //###WEAK: Create utility function like before???
        //	}
        //	if (_eBodySex == EBodySex.Shemale || _eBodySex == EBodySex.Man)
        //		_aSoftBodies.Add(_oPenis = (CPenis)CBMesh.Create(null, this, _sNameGameBody, "_Detach_Penis", "Client", "gBL_GetMesh", "'NoSkinInfo'", typeof(CPenis)));
        //	if (_eBodySex == EBodySex.Woman)
        //		_oVagina = new CVagina(this);

        //	//=== Create the important body collider that will repel fluid in the scene ===
        //	_oBodyCol = (CBBodyCol)CBBodyCol.Create(null, this, _sNameGameBody);
        //}

        //=== Obtain the source mesh body for normal extraction ===
        ///_oBodySource = CBMesh.Create(null, this, "oMeshSource", typeof(CBMesh));
		///_oBodySource.GetComponent<MeshRenderer>().enabled = false;					// This mesh is to pull normals only.  Not visible at runtime!


        //===== MAIN SKINNED BODY PROCESSING =====
        //=== Get the main body skinned mesh (has to be done once all softbody parts have been detached) ===
        _oBodySkinnedMesh = (CBSkin)CBMesh.Create(_oBodyRootGO, this, "oMeshBody", typeof(CBSkin));
        //_oBodySkinnedMesh.GetComponent<SkinnedMeshRenderer>().enabled = false;

        //###F
        _oBodyFlexCldr = (CBSkin)CBMesh.Create(null, this, "oMeshFlexCldr", typeof(CBSkin));
        _oBodyFlexCldr.gameObject.AddComponent<CFlexSkinned>();
        _oBodyFlexCldr.GetComponent<SkinnedMeshRenderer>().enabled = false;

        //=== Create a hotspot at the character's head the user can use to invoke our (important) context menu ===
        Transform oHeadT = FindBone("chest/neck/head");         // Our hotspot is located on the forehead of the character.
		_oHotSpot = CHotSpot.CreateHotspot(this, oHeadT, this._sHumanCharacterName, false, new Vector3(0, 0.09f, 0.03f), 2.0f);     //###IMPROVE: Get these offsets from pre-placed nodes on bone structure??

        ////=== Create the head look controller to look at parts of the other body ===
        _oHeadLook = _oBodyRootGO.gameObject.AddComponent<CHeadLook>();			//####DESIGN: Keep for morph mode??
		_oHeadLook.OnStart(this);


		//=== Instantiate the requested hair and pin as child of the head bone ===
		EBodyHair eBodyHair = (EBodyHair)_oObj.PropGet(EBodyDef.Hair);
		if (eBodyHair != EBodyHair.None) {
			string sNameHair = "HairW-" + eBodyHair.ToString();         //###HACK!!! W extension!		###HACK!!!! Man support!!
			GameObject oHairTemplateGO = Resources.Load("Models/Characters/Woman/Hair/" + sNameHair + "/" + sNameHair, typeof(GameObject)) as GameObject;   // Hair has name of folder and filename the same.	//###HACK: Path to hair, selection control, enumeration, etc
			_oHairGO = GameObject.Instantiate(oHairTemplateGO) as GameObject;
			Transform oBoneHead = FindBone("chest/neck/head");
			_oHairGO.transform.parent = oBoneHead;
			_oHairGO.transform.localPosition = Vector3.zero;
			_oHairGO.transform.localRotation = Quaternion.identity;
			if (_eBodySex == EBodySex.Man) {            //###HACK!!!!!! To reuse messy hair for man!!
				_oHairGO.transform.localPosition = new Vector3(0, 0.0f, 0.0f);
				_oHairGO.transform.localScale = new Vector3(1.07f, 1.07f, 1.08f);
			}
		}

        Body_InitActors();

		////=== Setup the keys to handle penis control on non-woman bodies ===
		//if (_eBodySex != EBodySex.Woman) {      //###MOVE?        ###OBS ###F
		//	bool bSelectedBodyOnly = (CGame.INSTANCE._nNumPenisInScene_BROKEN > 1);    // Keys below are active if this body is the selected body ONLY if we have more than one man in the scene
		//	if (_oPenis != null) {
		//		_oKeyHook_PenisBaseUpDown = new CKeyHook(_oPenis._oObjDriver.PropFind(EPenis.BaseUpDown), KeyCode.Q, EKeyHookType.QuickMouseEdit, "Penis up/down", 1, bSelectedBodyOnly);
		//		_oKeyHook_PenisShaftUpDown = new CKeyHook(_oPenis._oObjDriver.PropFind(EPenis.ShaftUpDown), KeyCode.E, EKeyHookType.QuickMouseEdit, "Penis bend up/down", 1, bSelectedBodyOnly);
		//		_oKeyHook_PenisDriveStrengthMax = new CKeyHook(_oPenis._oObjDriver.PropFind(EPenis.DriveStrengthMax), KeyCode.G, EKeyHookType.QuickMouseEdit, "Penis erection", -1, bSelectedBodyOnly);
		//	}
		//}
		_oKeyHook_ChestUpDown = new CKeyHook(_oActor_Chest._oObj.PropFind(EActorChest.Chest_UpDown), KeyCode.T, EKeyHookType.QuickMouseEdit, "Chest forward/back");

		//=== Create the face and its associated morph channels ===
		_oFace = (CFace)CBMesh.Create(null, this, "oMeshFace", typeof(CFace));

		//=== Reparent our actor base to the pose root so that user can move / rotate all bodies at once ===
		_oActor_Base.transform.parent = CGame.INSTANCE._oPoseRoot.transform;
		_oActor_Base.gameObject.name = _sBodyPrefix + "_Base";

		//=== Copy references to our actors to our script-friendly CObject variables to provide friendlier access to our scriptable objects ===
		Base    = _oActor_Base._oObj;              // CGamePlay passed us the reference to the right (empty) static object.  We fill it here.
		Chest   = _oActor_Chest._oObj;
		Torso   = _oActor_Torso._oObj;
		Pelvis  = _oActor_Pelvis._oObj;
		ArmL    = _oActor_ArmL._oObj;
		ArmR    = _oActor_ArmR._oObj;
		LegL    = _oActor_LegL._oObj;
		LegR    = _oActor_LegR._oObj;
		Face    = _oFace._oObj;
		///###BROKEN ###DEVO Penis = (_oPenis == null) ? null : _oPenis._oObjDriver;

		_oScriptPlay = CUtility.FindOrCreateComponent(_oBodyRootGO.transform, typeof(CScriptPlay)) as CScriptPlay;
		_oScriptPlay.OnStart(this);

		//=== Rotate the 2nd body toward the first and separate slightly loading poses doesn't pile up one on another ===	####MOVE? ####OBS? (Depend on pose?)
		//####PROBLEM: Set separation and don't do in all game modes
		if (_nBodyID == 0) {
			_oActor_Base.transform.position = new Vector3(0, 0, -CGame.C_BodySeparationAtStart);        //###DESIGN: Don't load base actor instead??  ###BUG Overwrites user setting of base!!!!
		} else {
			_oActor_Base.transform.position = new Vector3(0, 0, CGame.C_BodySeparationAtStart);
			_oActor_Base.transform.rotation = Quaternion.Euler(0, 180, 0);      // Rotate the 2nd body 180 degrees
		}

        ///_oClothEdit_HACK = new CClothEdit(this, "Shirt");

        ///CGame.gBL_SendCmd("CBody", "CBody_GetBody(" + _nBodyID.ToString() + ").Breasts_ApplyMorph('RESIZE', 'Nipple', 'Center', 'Wide', (1.6, 1.6, 1.6, 0), None)");       //###F ###HACK!!!

        //=== Create the left and right canvases on each side of the body so that panels have a place to be pinned for close-to-body editing ===
        _aUICanvas[0] = CUICanvas.Create(_oActor_Torso.transform.FindChild("_CanvasPin_Left"));        //###HACK
        _aUICanvas[1] = CUICanvas.Create(_oActor_Torso.transform.FindChild("_CanvasPin_Right"));
    }


    public void Body_InitActors() {
		//=== Fetch the body part components, assign them to easy-to-access variables (and a collection for easy iteration) and initialize them by telling them their 'side' ===
		_aActors.Add(_oActor_Base	= _oBodyRootGO.transform.FindChild("Base")				.GetComponent<CActorNode>());
		_aActors.Add(_oActor_Torso	= _oBodyRootGO.transform.FindChild("Base/Torso")		.GetComponent<CActorNode>());
		_aActors.Add(_oActor_Chest	= _oBodyRootGO.transform.FindChild("Base/Torso/Chest")	.GetComponent<CActorChest>());
		_aActors.Add(_oActor_Pelvis	= _oBodyRootGO.transform.FindChild("Base/Torso/Pelvis").GetComponent<CActorPelvis>());
		_aActors.Add(_oActor_ArmL	= _oBodyRootGO.transform.FindChild("Base/ArmL")		.GetComponent<CActorArm>());
		_aActors.Add(_oActor_ArmR	= _oBodyRootGO.transform.FindChild("Base/ArmR")		.GetComponent<CActorArm>());
		_aActors.Add(_oActor_LegL	= _oBodyRootGO.transform.FindChild("Base/LegL")		.GetComponent<CActorLeg>());
		_aActors.Add(_oActor_LegR	= _oBodyRootGO.transform.FindChild("Base/LegR")		.GetComponent<CActorLeg>());

		foreach (CActor oActor in _aActors)
			oActor.OnStart(this);
	}

	public void Destroy() {             //###BUG: We sure as heck don't destroy everything... ###IMPROVE!
		Debug.Log("CBody.OnDestroy(): " + _sBodyPrefix);
		foreach (CActor oActor in _aActors)
			GameObject.DestroyImmediate(oActor);

		GameObject.DestroyImmediate(_oActor_Base.gameObject);          // Destroy our body's entry in top-level CPoseRoot

		//if (_oKeyHook_PenisBaseUpDown != null) _oKeyHook_PenisBaseUpDown.Dispose();     //###WEAK!!! Try to enable auto-dispose!!
		//if (_oKeyHook_PenisShaftUpDown != null) _oKeyHook_PenisShaftUpDown.Dispose();
		//if (_oKeyHook_PenisDriveStrengthMax != null) _oKeyHook_PenisDriveStrengthMax.Dispose();
		if (_oKeyHook_ChestUpDown != null) _oKeyHook_ChestUpDown.Dispose();

		foreach (CBCloth oBCloth in _aCloths)
			GameObject.DestroyImmediate(oBCloth.gameObject);
		//if (_oBSkinRim != null)
		//	GameObject.DestroyImmediate(_oBSkinRim);
	}

	
	//---------------------------------------------------------------------------	UPDATE

	public void OnSimulatePre() {
   //     if (_oBSkinRim != null)
			//_oBSkinRim.OnSimulatePre();					// The very first thing we do is to get our rim to update itself so all pin positions for this frame will be refreshed...

		//if (_oVagina != null)
		//	_oVagina.OnSimulatePre();
	
		foreach (CBSoft oBSoft in _aSoftBodies)
			oBSoft.OnSimulatePre();

		_oHeadLook.OnSimulatePre();

		//=== Arm pinning key state preocessing ===  Space = set close to camera arm, LeftAlt = faraway from camera arm
		if (Input.GetKey(KeyCode.Space) || Input.GetKey(KeyCode.LeftAlt)) {		// If we begin press to its key we begin the mode, optionally getting an arm to update.  we keep updating while the key is pressed and end the state on key up
			if (Input.GetKeyDown(KeyCode.Space) || Input.GetKeyDown(KeyCode.LeftAlt)) {
				CActorArm oArm = FindCloseOrFarArmFromCamera(Input.GetKeyDown(KeyCode.LeftAlt));	
				if (oArm != null) {
					_oArm_SettingRaycastPin = oArm;
					_oArm_SettingRaycastPin.ArmRaycastPin_Begin();
				}
			}
			if (_oArm_SettingRaycastPin != null)
				_oArm_SettingRaycastPin.ArmRaycastPin_Update();
		}
		if (_oArm_SettingRaycastPin != null && (Input.GetKeyUp(KeyCode.Space) || Input.GetKeyUp(KeyCode.LeftAlt))) {	//###LEARN: When GetKeyUp is true GetKey is false!
			_oArm_SettingRaycastPin.ArmRaycastPin_End();
			_oArm_SettingRaycastPin = null;
		}

		_oActor_ArmL.OnSimulatePre();		//###OBS? Arms need per-frame update to handle pinning to bodycol verts
		_oActor_ArmR.OnSimulatePre();

		//=== Execute ejaculation if selected body and the pertinent global property is set ===//###BUG!!!!: Won't correctly process two of the same sex!!!
		//if (_bIsCumming) {        ###DEVO ###OBS: Old Fluid
		//	if (_eBodySex == EBodySex.Woman) {		//###IMPROVE!!!!!: Woman cum can be a lot better!

		//		//=== Set the position of the one fluid emitter instance to transform position of vagina entrance bone ===
		//		ErosEngine.Object_SetPositionOrientation(CGame.INSTANCE._oFluid._oObj._hObject, 0, _oVagina._oVaginaCumEmitterT.position, _oVagina._oVaginaCumEmitterT.rotation);	// Update the position of our fluid.  Penis tip controls the location of this global object // If woman body is selected and we're cumming place the one fluid emitter at the 'Vagina-CumEmitter' bone

		//		float nCycleTime = 8;		//###TUNE	###IMPROVE: Give user GUI access to these??
		//		float nMaxRate = 300;		//###TUNE!!!
		//		CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitVelocity, 0.00f);		//###TUNE

		//		//=== Set the emit velocity & rate from the pertinent configuration curve ===
		//		float nTimeInEjaculationCycle = (Time.time - CGame.INSTANCE._nTimeStartOfCumming) % nCycleTime;
		//		float nTimeInEjaculationCycle_Normalized = nTimeInEjaculationCycle / nCycleTime;		//###DESIGN!!! Move curve here?  How to persist??
		//		float nEmitRate = nMaxRate * Mathf.Max(CGame.INSTANCE.CurveEjaculateWoman.Evaluate(nTimeInEjaculationCycle_Normalized), 0);		//###NOTE: We assume both the ejaculation curve's X (time) value and Y values (strenght) go from 0 to 1

		//		CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitRate, nEmitRate);		// Woman ejaculation is a rate-based emitter where we control the rate over time	###DESIGN: Would going pressure-base like man have any sense here??

		//	} else {

		//		//=== Set the position of the one fluid emitter instance to transform position of penis tip ===
		//		ErosEngine.Object_SetPositionOrientation(CGame.INSTANCE._oFluid._oObj._hObject, 0, _oPenis._oPenisTip._oHotSpot.transform.position, _oPenis._oPenisTip._oHotSpot.transform.rotation);	// Update the position of our fluid.  Penis tip controls the location of this global object	// If man's body is selected place at hotspot of penis tip conveniently located at uretra.

		//		float nCycleTime	= _oPenis._oPenisTip._oObj.PropGet(EPenisTip.CycleTime);
		//		float nMaxVelocity	= _oPenis._oPenisTip._oObj.PropGet(EPenisTip.MaxVelocity);

		//		//=== Set the emit velocity & rate from the pertinent configuration curve ===
		//		float nTimeInEjaculationCycle = (Time.time - CGame.INSTANCE._nTimeStartOfCumming) % nCycleTime;
		//		float nTimeInEjaculationCycle_Normalized = nTimeInEjaculationCycle / nCycleTime;		//###DESIGN!!! Move curve here?  How to persist??
		//		float nEmitVelocity = nMaxVelocity * Mathf.Max(CGame.INSTANCE.CurveEjaculateMan.Evaluate(nTimeInEjaculationCycle_Normalized), 0);		//###NOTE: We assume both the ejaculation curve's X (time) value and Y values (strenght) go from 0 to 1

		//		CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitVelocity, nEmitVelocity);	// Man ejaculation is a pressure-based emitter where we control the emit velocity over time
		//		float nEmitRate = (nEmitVelocity != 0) ? 10000 : 0;		//###WEAK: What max??  ramp up??  threshold point??	// Set a very large rate as we're a pressure-based emitter... (we are limited by neighborhood particles)
		//		CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitRate, nEmitRate);
		//	}
		//}
		if (Input.GetKeyDown(KeyCode.R))		//###DESIGN: Selected only??
			ResetPinsToBones();
    }

    public void SetBodiesAsKinematic(bool bBodiesAreKinematic) {       // Set body as kinematic or not (used for pose loading / teleportation)
        EGameModes eGameModeSrc = EGameModes.Configure;
        EGameModes eGameModeDst = EGameModes.Play;
        if (bBodiesAreKinematic) {
            eGameModeSrc = EGameModes.Play;
            eGameModeDst = EGameModes.Configure;
        }
        foreach (CActor oActor in _aActors)
            oActor.OnChangeGameMode(eGameModeDst, eGameModeSrc);        //###DESIGN Closely related to game mode... merge in within a new game mode??
    }

    public void HoldSoftBodiesInReset(bool bSoftBodyInReset) {                       // Reset softbodies to their startup state.  Essential during pose load / teleportation!
        foreach (CBSoft oBody in _aSoftBodies)
            oBody.HoldSoftBodiesInReset(bSoftBodyInReset);
    }

    public void OnSimulateBetweenPhysX23() {
		//foreach (CBSoft oBSoft in _aSoftBodies)					// First simulate the PhysX2 soft bodies
		//	oBSoft.OnSimulateBetweenPhysX23();
		foreach (CBCloth oBCloth in _aCloths)					// Simulate the PhysX3 cloths from the just-updated colliders above
			oBCloth.OnSimulateBetweenPhysX23();
		//if (_oBodyCol != null)			//###NOTE: CBodyCol needs to simulate AFTER breasts as these have to push their global colliders for per-frame CBodyCol code to pick them up for this frame.
		//	_oBodyCol.OnSimulatePre();		//###CHECK: Move to later breaks anything??
	}

	public void OnSimulatePost() {
		foreach (CBSoft oBSoft in _aSoftBodies)			//###CHECK: Cloth fitting mode needs breast to run, but others???
			oBSoft.OnSimulatePost();
		foreach (CBCloth oBCloth in _aCloths)
			oBCloth.OnSimulatePost();
	}


	//---------------------------------------------------------------------------	EDIT-TIME BONE UPDATE FROM BLENDER

	public void UpdateBonesFromBlender() {						// Update our body's bones from the current Blender structure... Launched at edit-time by our helper class CBodyEd
		_oBonesT = _oBodyRootGO.transform.FindChild("Bones");

		string sNameBodySrc = _sBodyPrefix;			//####BROKEN?
		if (sNameBodySrc.StartsWith("Prefab") == false)
			throw new CException("UpdateBonesFromBlender could not recognize PrefabXXX game object name " + sNameBodySrc);
		sNameBodySrc = sNameBodySrc.Substring(6);			// Remove 'Prefab' to obtain Blender body source name (a bit weak)
		CMemAlloc<byte> memBA = new CMemAlloc<byte>();
		CGame.gBL_SendCmd_GetMemBuffer("'Client'", "gBL_GetBones('" + sNameBodySrc + "')", ref memBA);		//###TODO: get body type from enum in body plus type!	//oBody._sMeshSource + 
		byte[] oBA = (byte[])memBA.L;
		int nPosBA = 0;

		//=== Decrypt the bytes array that Blender Python prepared for us in 'gBL_GetBones()' ===
		ushort nMagicBegin = BitConverter.ToUInt16(oBA, nPosBA); nPosBA += 2;		// Read basic sanity check magic number at start
		if (nMagicBegin != G.C_MagicNo_TranBegin)
			throw new CException("ERROR in CBodyEd.UpdateBonesFromBlender().  Invalid transaction begin magic number!");

		//=== Read the recursive bone tree.  The mesh is still based on our bone structure which remains authoritative but we need to map the bone IDs from Blender to Unity! ===
		ReadBone(ref oBA, ref nPosBA, _oBonesT);		//###IMPROVE? Could define bones in Unity from what they are in Blender?  (Big design decision as we have lots of extra stuff on Unity bones!!!)

		CUtility.BlenderSerialize_CheckMagicNumber(ref oBA, ref nPosBA, true);				// Read the 'end magic number' that always follows a stream.

		Debug.Log("+++ UpdateBonesFromBlender() OK +++");
	}

	void ReadBone(ref byte[] oBA, ref int nPosBA, Transform oBoneParent) {							// Precise opposite of gBlender.Stream_SendBone(): Reads a bone from Blender, finds (or create) equivalent Unity bone and updates position
		string sBoneName = CUtility.BlenderStream_ReadStringPascal(ref oBA, ref nPosBA);
		Vector3	vecBone = CUtility.ByteArray_ReadVector(ref oBA, ref nPosBA);
		Transform oBone = oBoneParent.FindChild(sBoneName);
		if (oBone == null) {
			oBone = new GameObject(sBoneName).transform;
			oBone.parent = oBoneParent;
			Debug.LogWarning(string.Format("ReadBone created new bone '{0}' under parent '{1}' and set to position {2:F3},{3:F3},{4:F3}", sBoneName, oBoneParent.name, vecBone.x, vecBone.y, vecBone.z));
		} else {
			Debug.Log(string.Format("ReadBone updated bone '{0}' under parent '{1}' and set position {2:F3},{3:F3},{4:F3}", sBoneName, oBoneParent.name, vecBone.x, vecBone.y, vecBone.z));
		}
		oBone.position = vecBone;
		int nBones = oBA[nPosBA++];
		for (int nBone = 0; nBone < nBones; nBone++)
			ReadBone(ref oBA, ref nPosBA, oBone);
	}


	//---------------------------------------------------------------------------	UTILITY

	public void ResetPinsToBones() {
		ResetPinToBone("Torso", "chest/abdomen");
		ResetPinToBone("Torso/Chest", "chest");
		ResetPinToBone("Torso/Pelvis", "chest/abdomen/hip");		//###NOTE: DAZ's hip bone = our pelvis
		ResetPinToBone("Torso", "chest/abdomen");					//###WEAK: ###CHECK???  Do it twice because of different parent child relationhips between the two trees... needed???
		ResetPinToBone("Torso/Chest", "chest");
		ResetPinToBone("Torso/Pelvis", "chest/abdomen/hip");		
	}
	public void ResetPinToBone(string sPathPin, string sPathBone) {		//###IMPROVE: Fix to run during play-time... Have to re-root from CPoseRoot
		Transform oRootPinT = (_oActor_Base != null) ? _oActor_Base.transform : _oBodyRootGO.transform.FindChild("Base");	// If we're in game mode we can fetch base actor, if not we have to find Bones node off our prefab tree
		Transform oRootBoneT = _oBodyRootGO.transform.FindChild("Bones");
		Transform oPinT = oRootPinT.FindChild(sPathPin);
		Transform oBoneT = oRootBoneT.FindChild(sPathBone);
		oPinT.position = oBoneT.position;
	}
	public Transform FindBone(string sBonePath) {
		Transform oBoneT = _oBonesT.FindChild(sBonePath);
		if (oBoneT == null)
			throw new CException(string.Format("ERROR: CBody.FindBone() cannot find bone '{0}'", sBonePath));
		return oBoneT;
	}
	public Transform SearchBone(Transform oParentT, string sBoneName) {		// Recursive function that searches our entire bone tree for node name (slow!!)
		if (oParentT.name == sBoneName)
			return oParentT;
		for (int nChild = 0; nChild < oParentT.childCount; nChild++) {
			Transform oChild = oParentT.GetChild(nChild);
			Transform oFoundBone = SearchBone(oChild, sBoneName);
			if (oFoundBone != null)
				return oFoundBone;
		}
		return null;
	}
	public void SelectBody() {
		CGame.INSTANCE._nSelectedBody = _nBodyID;
		CGame.SetGuiMessage(EGameGuiMsg.SelectedBody, _sHumanCharacterName);
	}
	public bool IsBodySelected() {
		return CGame.INSTANCE._nSelectedBody == _nBodyID;
	}
	public CActorArm FindCloseOrFarArmFromCamera(bool bInvert) {		// Used by hand placement functionality to auto-select the hand to move without user selection
		if (IsBodySelected()) {		// Only the closest arm of the selected body responds
			float nDistL = (_oActor_ArmL._oJointShoulder._oTransform.position - Camera.main.transform.position).magnitude;
			float nDistR = (_oActor_ArmR._oJointShoulder._oTransform.position - Camera.main.transform.position).magnitude;
			if (bInvert)
				return (nDistL < nDistR) ? _oActor_ArmR : _oActor_ArmL;
			else
				return (nDistL < nDistR) ? _oActor_ArmL : _oActor_ArmR;
		} else {
			return null;
		}
	}
	public static string GetNameGameBodyFromPrefix(int nBodyID) {		// Returns the important prefix to many Blender-side objects / meshes related to constucting this CBody... 
		char chBodyID = (char)(65 + nBodyID);			// Convert the 0-based numeric ID into A,B,C,D,E...
		return "Body" + chBodyID;						// Body prefixes look like 'BodyA', 'BodyB', etc
	}
	public void SetIsCumming(bool bIsCumming) {	// Only one character can cum at a time as there is only one fluid.  Configure the fluid for our usage
		_bIsCumming = bIsCumming;

		if (_bIsCumming) {
			if (_eBodySex == EBodySex.Woman) {
				//CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitType, (int)EChoice_EmitType.Rate);
				//_oObj.PropSet(EFluid.Fluid_Gravity, 0.2f);
				//_oObj.PropSet(EFluid.EmitHeightRatio, 4);			//###TODO: Much greater randomness, etc

			} else {
                //CGame.INSTANCE._oFluid._oObj.PropSet(EFluid.EmitType, (int)EChoice_EmitType.Pressure);
            }
        }
	}

    public void HideShowMeshes(bool bShowPresentation, bool bShowPhysxColliders, bool bShowMeshStartup, bool bShowPinningRims, bool bShowFlexSkinned, bool bShowFlexColliders, bool bShowFlexParticles) {
        _oBodySkinnedMesh._oSkinMeshRendNow.enabled = bShowPresentation;
        _oFace.GetComponent<MeshRenderer>().enabled = bShowPresentation;
        _oHairGO.GetComponent<MeshRenderer>().enabled = bShowPresentation;
        _oBodyFlexCldr._oSkinMeshRendNow.enabled = bShowFlexColliders;
        if (_oBodyFlexCldr.GetComponent<uFlex.FlexParticlesRenderer>() != null)
            _oBodyFlexCldr.GetComponent<uFlex.FlexParticlesRenderer>().enabled = bShowFlexParticles;

        foreach (CBSoft oSoftBody in _aSoftBodies)
            oSoftBody.HideShowMeshes(bShowPresentation, bShowPhysxColliders, bShowMeshStartup, bShowPinningRims, bShowFlexSkinned, bShowFlexColliders, bShowFlexParticles);
        foreach (CBCloth oCloth in _aCloths)
            oCloth.HideShowMeshes(bShowPresentation, bShowPhysxColliders, bShowMeshStartup, bShowPinningRims, bShowFlexSkinned, bShowFlexColliders, bShowFlexParticles);
    }



    //---------------------------------------------------------------------------	LOAD / SAVE
    public bool Pose_Load(string sNamePose) {
		string sPathPose = CGame.GetPathPoseFile(sNamePose);
		if (File.Exists(sPathPose) == false) {
			Debug.LogError("CBody.Pose_Load() could not find file " + sPathPose);
			return false;
		}
		_sNamePose = sNamePose;
		_oActor_Pelvis._eAnimMode = EAnimMode.Stopped;		// Cancel animation on sex bone on pose load
		CGame.INSTANCE.Cum_Stop();			// Stop & clear cum upon a pose loading on any body.

		_oScriptPlay.LoadScript(sPathPose);
		_oScriptPlay.ExecuteAll();			// Execute all statements in file without pausing

		CGame.INSTANCE.TemporarilyDisablePhysicsCollision();

		Debug.Log(string.Format("Pose_Load() on body '{0}' loaded '{1}'", _sBodyPrefix, _sNamePose));
		return true;
	}
	public void Pose_Save(string sNamePose) {
		_sNamePose = sNamePose;
		Directory.CreateDirectory(CGame.GetPathPoses() + _sNamePose);					// Make sure that directory path exists
		string sPathPose = CGame.GetPathPoseFile(_sNamePose);
		CScriptRecord oScriptRec = new CScriptRecord(sPathPose, "Body Pose " + sPathPose);
		foreach (CActor oActor in _aActors)
			if (oActor != _oActor_Base)						// We do not save the base actor.  User orients this to position the body in the scene.
				oScriptRec.WriteObject(oActor._oObj);
		Debug.Log(string.Format("Pose_Save() on body '{0}' saved '{1}'", _sBodyPrefix, _sNamePose));
	}
	public void Pose_Reload() {
		Pose_Load(_sNamePose);
	}
	
	public void Serialize_Actors_OBS(FileStream oStream) {
		foreach (CActor oActor in _aActors)
			oActor.Serialize_OBS(oStream);
	}


	public void OnChangeGameMode(EGameModes eGameModeNew, EGameModes eGameModeOld) {        //###DEV
		foreach (CBSoft oBSoft in _aSoftBodies)
			oBSoft.OnChangeGameMode(eGameModeNew, eGameModeOld);
		foreach (CActor oActor in _aActors)
			oActor.OnChangeGameMode(eGameModeNew, eGameModeOld);
	}


	//--------------------------------------------------------------------------	IOBJECT INTERFACE
	public void OnPropSet_BreastSize(float nValueOld, float nValueNew) {		//####DEV ####TEMP: Abstract code for all sliders
		CGame.gBL_SendCmd("CBody", _sBlenderInstancePath_CBody + ".Breasts_ApplyMorph('RESIZE', 'Nipple', 'Center', 'Wide', (" + nValueNew.ToString() + "," + nValueNew.ToString() + "," + nValueNew.ToString() + ",0), None)");
		//UpdateVertsFromBlenderMesh(false);						// Update Unity's copy of the morphing body's verts.
		_oBreastL.UpdateVertsFromBlenderMesh(false);		//####DEV ###TEMP
		//_oBodyColBreast.UpdateVertsFromBlenderMesh(true);       // Update Unity's copy of the breast collider mesh
	}

	public void OnPropSet_BtnUpdateBody(float nValueOld, float nValueNew) {
		Debug.Log("CBody: Rebuilding body " + _sBodyPrefix);
		//Pose_Save("TEMP");				// Save the current pose to a temp file so we can restore body as it was right after rebuild
		CGame.INSTANCE.CreateBody(_nBodyID);		// Will destroy 'this' and rebuild entire new tree of objects & meshes all the way from Blender
		//Pose_Load("TEMP");				// Restore pose saved earlier
		CGame.INSTANCE.Scene_Reload();		//###HACK?  ###DESIGN: Reload whole scene to re-init position of newly created body
	}
	public void OnPropSet_NeedReset(CProp oProp, float nValueOld, float nValueNew) {}		//###DESIGN!!! Damn this near-useless function getting a pain in the ass...


	//--------------------------------------------------------------------------	IHotspot interface

	public void OnHotspotChanged(CGizmo oGizmo, EEditMode eEditMode, EHotSpotOp eHotSpotOp) { }
	public void OnHotspotEvent(EHotSpotEvent eHotSpotEvent, object o) {
		//###IMPROVE: Make this work by clicking on head? _oBody.SelectBody();			// Doing anything with a body's hotspot (head) selects the body
		if (eHotSpotEvent == EHotSpotEvent.ContextMenu)
			_oHotSpot.WndPopup_Create(this, new CObject[] { _oObj /*, _oFace._oObj*/ });		//###TEMP: Face??
	}
}

public enum EBodySide {
	Left,
	Right,
}
